### ISSUE TITLE
local-api container fails to start

### ISSUE THREAD

**Issue by carlosdamassilva** [european-dynamics-rnd/OneNet#1]
![image](https://user-images.githubusercontent.com/93705107/184117456-803e74ab-f764-4c9a-a0a6-f6f8ae5d269d.png)

When deploying the docker stack, all the containers start and run except for the local-api, which keeps restarting, appearing the following message:

> exec /opt/scripts/start.sh: no such file or directory

I checked and the start.sh file is being correctly copied to the right container location. Could this be related to the operative system? I'm currently using Windows 11 with WSL.

**Comment by vsakas** [comment]
The development team will take care of this issue in a dew days, due to holidays.

**Comment by HeliasEurodyn** [comment]
Hello Carlos, 

The issue is fixed. 
Please download and rerun the docker-compose.yml file.

**Comment by kotsalosKon** [comment]
@carlosdamassilva
