### ISSUE TITLE
Get File From Provider - not work

### ISSUE THREAD

**Issue by cchara63** [european-dynamics-rnd/OneNet#10]
Hello,

With our IT help, we expose ports in public through Reverse Proxies for Data App and Ecc Url as shown below:  

![Figures](https://user-images.githubusercontent.com/106663426/200767187-eb156b25-5bc6-4641-80ba-94c13c8e7bc2.png)

after this, we tried to upload / download documents between two usernames (user1-PC1) and (user2-PC2-server/docker) with "Provide data / Consume data" functions. This has worked for some times correctly and then stopped. Now the system shows as error "Code 500" when we try to "Get File From Provider" . 

Please for your help,
Charalambos from UCY - KIOS

**Comment by HeliasEurodyn** [comment]
Hello cchara63. A new version is coming this week. There are diagnostics and new features there that will indicate us where is the missing part on your connections. I will get back with more instructions after the upgrade to the new version.

**Comment by cchara63** [comment]
ok, thank you!
