### ISSUE TITLE
Local API new version - where?

### ISSUE THREAD

**Issue by adeimv** [european-dynamics-rnd/OneNet#11]
Hello,
When I run the local app and check connectivity it is successful, but I get an alert that my local API version is old, and I should update it. Where can I find the new version? If I download from the "Documents & Downloads" I get again version 1.2.
Thank you in advance

**Comment by HeliasEurodyn** [comment]
Hello adeimv. A new version is coming this week. You will get wiki pages of instructions on how to upgrade to new version and new features available.

**Comment by vsakas** [comment]
The following text has been sent to all OneNet participants two days ago:
--------------------------------

Dear OneNet colleagues,

we would like to inform you that an updated version of the OneNet connector has been released.

With this update:
- Demos can communicate with the connector through APIs
- The GUI module is deployed locally along with the OneNet connector.
Existing deployments must re-deploy the S/W.

Deployment Instructions are provided here:
https://github.com/european-dynamics-rnd/OneNet/wiki/OneNet-Upgrade-Guide-to-the-Latest-Version 

Instructions for accessing the APIs are provided in:
https://github.com/european-dynamics-rnd/OneNet/wiki/Provide-&-Consume--Data-Through-Rest-Api 

Documentation is accessible on-line from the GUI menu.

For any comments etc. please use only the “issues” functionality in github. Also consult previous issues (including closed issues) before opening a new one.

We share this information with all participants in the mailing lists of WP7-WP11 as we presume that they might be interested in this update.


Best regards,


the OneNet development Team.
