### ISSUE TITLE
Attributes of API

### ISSUE THREAD

**Issue by barkalinowski** [european-dynamics-rnd/OneNet#14]
Dear all,

we are implementing connection between our PL DEMO platform and OneNet System through your API. We are almost done with everything, but we approached some wall. During downloading a file from "Consume data" (rq /api/consume-data/by-id) we get file in Base64, which is ok, but we are not able to retrieve the name and the **extension** of the file. If we would use only one data extension, there wouldn't be any problem, but I believe the extension is not standarized and we can send .xlsx, .csv .xml .txt etc. extensions. Is there any possibility that you will add attribute of the name of the file and the extension of the file(even through page or the list of consume data request). Or maybe there is the information about name and file extension in the API?

**Comment by HeliasEurodyn** [comment]
Hello barkalinowski,
have a look on this wiki page that expain this process
https://github.com/european-dynamics-rnd/OneNet/wiki/Provide-&-Consume--Data-Through-Rest-Api 

You can also access the swagger on the url 
<Server that you deployed onenet containers>:30001/api/swagger-ui/index.html?configUrl=/api/v3/api-docs/swagger-config

Indeed on the /api/consume-data/by-id you cannot get the filename or extension of the file. 

So first use the endpoint /consume-data/page/{page} to get the latest files' metadata (with id, filename etc) that you can consume.
On this endpoint you can find the filename of the file.  This field contains the filename WITH this extension like 'my_file.xml'. 

Generally the steps to consume are 

1. First use the /user/auth endpoint to login programmaticaly, copy the token to use it to the next endpoints
2. Then use the /consume-data/page/{page} endpoint to get the latest files' metadata (with id, filename etc) that you can consume 
3. Finally use the /consume-data/by-id to retrieve the actual files.

It is the same process that we use on the Ui to consume files with filenames and it is fully functional, so procced this way. 

I will advice the devs team to provide a separate field for the file extension on a next version of Onenet

**Comment by barkalinowski** [comment]
Hi Helias,

thank for your response. We have checked API's response from swagger and I have to partly disagree. /consume-data/page/{page} sends filename indeed, but without extension:
![image](https://user-images.githubusercontent.com/70036239/230388932-28795a6a-5e29-405d-a8c7-456b4743195f.png)
This is the case for every file we have uploaded to OneNet System GUI. Maybe we are doing something wrong with file uploading and there is no info about extension?

**Comment by HeliasEurodyn** [comment]
Yes you are right, the filename is missing from your response.
The 'data_title' you are showing is not the correct field. 

A new field 'file_name' was just added to this rest call. You dont need to do anything to get this update, this was done centrally. 
Just try once more and tell us if you are receiving this field called 'file_name' that contain the filename with the extension.

**Comment by barkalinowski** [comment]
Hi Helias,

thank you for your response. I can confirm that field "file_name" is in rest call and it meets our expectations. Thank you very much. 

One more thing only - not sure if it is on our side, because of still undergoing installation of docker containers on our premises, but in response we get the same set of data twice. i.e.:
![image](https://user-images.githubusercontent.com/70036239/231751137-42ee0036-dcaf-40a1-a2df-e8434411dec0.png)
It does not impact our solutions in any ways, but I thought it is worth mentioning it to you.
