### ISSUE TITLE
Clearing House

### ISSUE THREAD

**Issue by AlexBoss111** [european-dynamics-rnd/OneNet#15]
Dear Helias,

In the Data exchanges Timeline feature seen in the user interface, we see the some information of the files being exchanged. Is it possible to add some more info to this? Is the clearing house centralized or is it on my side? I mean, am I able to configure what shows up in the Data exchange timeline?, if so I could try to do it myself, where can I go to change these configurations?

BR
A. Lucas (InescTec)

**Comment by HeliasEurodyn** [comment]
Hello Lucas, It is centralized indeed, it can be customized according to user's needs. The administrator can do that, so please write us what information do you need to require on this, and we will let you know if that is possible.
