### ISSUE TITLE
Installing Onenet Local Application on Mac

### ISSUE THREAD

**Issue by cchara63** [european-dynamics-rnd/OneNet#17]
The Onenetexe1_3.zip includes a .exe document to install the Application on a Windows PC. What about a Mac, how we can install the application on a Mac laptop?  

Thank you,
Charalambos

**Comment by christos-aslamatzidis** [comment]
Hi Charalambe, 
there is no need for using the exe file as the local api is dockerized in the new version. 
you can follow the OneNet Deployment guide here: https://github.com/european-dynamics-rnd/OneNet.
Remember that you can deploy onenet only in your premises according to the decentralized architecture.
The user interface is also dockerized and installed on your premises. 
It can be accessed through the url: http://the_ip_where_the_containers_are_installed:30003

**Comment by cchara63** [comment]
ok, thank you!
