### ISSUE TITLE
"Data App is not accessible from the web"

### ISSUE THREAD

**Issue by karljaats** [european-dynamics-rnd/OneNet#18]
Hello,
We are having persistent problems with getting the Data App to work correctly. 
Using our local UI at port 30003 when checking the Data App connection we get the "Data App is not accessible from the web" error message. 

![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/48bb8e87-eda3-4aa4-ad57-1f73ea780f1f)

However the ports should be exposed and the Data App /about/version url at https://onenet-dmz.cyber.ee/middleware-data/about/version works correctly (from outside our network as well) and gives the "1.0" response.

The docker_be-dataapp-provider_1 and docker_be-dataapp-consumer_1 containers show errors that are probably to blame for this. Both show "ERROR on starting Jetty Server: Is a directory" and "Error parsing HTTP request header" logs. Any help in tracking down what the issue might be would be appreciated.

![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/b54d3858-d0dc-4561-9318-6e1190f4be7b)
![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/fd7b6e41-7f6d-4785-b13a-90d21a2d04fb)

**Comment by HeliasEurodyn** [comment]
Hello karljaats. can you try once more the "Connection Check" buttons ? The problem is fixxed now. It was a false restriction from our central registry application to access your publicly exposed url due to enhanced security measures.

**Comment by karljaats** [comment]
The connection check now indeed responds with a success message so that is one problem solved.

However we are still unable to provide/consume data. No message is given in the UI but the data does not get uploaded. 
The docker_be-dataapp-provider_1 and docker_be-dataapp-consumer_1 containers still have the mentioned error logs on startup (did a reinstall to make sure) and docker_be-dataapp-consumer_1 gets additional error logs when attempting to provide data:

![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/fbc03b55-b7df-42a4-9152-e76f190b4486)

**Comment by pierluigi-linardi** [comment]
Hello Karljaats,
in the last log, i see that the data app is trying to invoke the broker url with the ip 172.17.0.1, however the machine ip is 192.168.21.23.
Try changing this value in .env file --> LOCAL_IP_PROVIDER_CONTEXT_BROKER=192.168.21.23 and restart the application.

**Comment by karljaats** [comment]
Hello
That was a good catch, but the error remained the same.
![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/d267a8ca-32b9-4af3-aa33-96503776789a)

**Comment by pierluigi-linardi** [comment]
Good Morning,
Could you check if the fiware-orion service is up?
In my case, I have this result via browser:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/15787703/fd3e96a3-647b-4fcc-9a6d-8e0dfa6362db)

**Comment by karljaats** [comment]
It is up.
![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/d7aeeece-45df-406b-8997-2607c277f21c)
The fiware-orion container even gets logs when I attempt to save provided data so at least something is connecting with it.
![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/4985e22e-9177-4c91-bec6-f2b71bd2cc51)

**Comment by ferdinandobosco** [comment]
Hi Karl, can you try to change the dataapp and ecc in http and try it again? It seems something related to protocols connection... 

If the error persists, we can arrange a technical meeting and try to fix it online.

Best,
Ferdinando

**Comment by karljaats** [comment]
It turned out that our nginx was only redirecting https requests to the url and so http requests were not getting through. Having fixed that but leaving the urls in the connector settings as they were, we are now able to successfully provide data. However consuming data is still not working.

The "Get file from provider" button under Consume Data seems to be failing without producing any logs at all but using the "Get File" button in the form for provided data produces a MultipartMessageException in docker_be-dataapp-consumer_1:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/7207857/d23ab27a-b996-4c7b-9035-f2f2aa99c52b)

PS http requests to our dataapp and ecc url from outside of our network currently remain blocked, but as far as I understand that communication should always be using https anyway and using http doesn't seem right. However If I am wrong about that then we can change that as well.

**Comment by ferdinandobosco** [comment]
Hi Karl,
did you try a clean run from the beginning (create new service, new data, new subscription etc...). If not, can you try it?

Can you please also share with us the entire logs of the containers? (both data apps, both ecc, etc..).

Thank you.

**Comment by karljaats** [comment]
I did a restart to the containers and then did a clean run from the beginning as suggested but it still behaved the same. Everything worked except for consuming data.

The logs for all containers:
[cyb_logs.zip](https://github.com/european-dynamics-rnd/OneNet/files/12594803/cyb_logs.zip)

**Comment by karljaats** [comment]
The remaining issue was in our local Nginx configuration that was interfering with the communication. Seems to be working now.
