### ISSUE TITLE
Problem docker-compose up -d 

### ISSUE THREAD

**Issue by mateoNester71** [european-dynamics-rnd/OneNet#3]
Good day,

After clonning the repository on the root `\opt\onenet-true-connector` , we executed the command: `docker-compose up -d`. However we received the following ERROR:

```
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
We already tried changing the version from 2.2 to 3.3, but the error is the same.

Can you please help us solve this issue.

Thank you for your kind help,
Mateo Toro (R&D Nester)

**Comment by tchouliaras** [comment]
@mateoNester71 remove the line 'name: "onenet-fiware-true-connector"' 

i have had the same problem out of the box. Removing this line solves this problem. (there is another, but i will open a ticket)

Kind Regards
Thanasis Chouliaras (Ubitech)

**Comment by mateoNester71** [comment]
Hello Thanasis,

Removing the line does solved the problem. Thank you. However, other issue pop-up. I will create a new issue.

Regards,
Mateo Toro (R&D Nester)

**Comment by tchouliaras** [comment]
@mateoNester71 Good to hear, however I am not sure you should close the ticket, I am not in the development team of ED and the connectors. They should decide if this is considered a bug or not. You can consider my answer as a workaround

**Comment by mateoNester71** [comment]
Understood Thanasis. I will reopen waiting for official confirmation.
Thanks

**Comment by ferdinandobosco** [comment]
Solved. Docker-compose file updated.
