### ISSUE TITLE
Not able to pull some of the images from private registry

### ISSUE THREAD

**Issue by tchouliaras** [european-dynamics-rnd/OneNet#4]
A docker-compose pull gives error in the two following images. All the rest are downloaded fine.

1. be-dataapp-provider
2. be-dataapp-consumer

The insecure repos have been added to the registry. 

maybe some rights are needed or some other IP added

Full output

```
[centos@esadtest docker]$ docker-compose pull
Pulling ecc-provider        ... done
Pulling uc-dataapp-provider ... done
Pulling be-dataapp-provider ... error
Pulling ecc-consumer        ... done
Pulling uc-dataapp-consumer ... done
Pulling be-dataapp-consumer ... error
Pulling mongo-db            ... done
Pulling orion               ... done

ERROR: for be-dataapp-provider  Get "https://109.232.32.194:5000/v2/": http: server gave HTTP response to HTTPS client

ERROR: for be-dataapp-consumer  Get "https://109.232.32.194:5000/v2/": http: server gave HTTP response to HTTPS client
ERROR: Get "https://109.232.32.194:5000/v2/": http: server gave HTTP response to HTTPS client
Get "https://109.232.32.194:5000/v2/": http: server gave HTTP response to HTTPS client
```

Kind Regards
Thanasis Chouliaras (Ubitech)

**Comment by ferdinandobosco** [comment]
The error seems still related to the insecure registry. Did you restart docker daemon after the change?

**Comment by tchouliaras** [comment]
@ferdinandobosco  Yes I tried that also, even after restart I cannot pull the images. I see others opened the same ticket.

**Comment by ferdinandobosco** [comment]
Solved. Docker images is now available on Docker Hub public repo.
