### ISSUE TITLE
Docker Settings insecure-registries Timeout

### ISSUE THREAD

**Issue by mateoNester71** [european-dynamics-rnd/OneNet#5]
Good afternoon,

While executing the `compose` command, the pulling of the `be-dataapp-provider` failed with a Timeout ERROR message. 

```
Pulling be-dataapp-provider (109.232.32.194:5000/onenet-connector-fiware-data-app:0.1)...
ERROR: Get "https://109.232.32.194:5000/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

We are using Docker Desktop, and included the insecure-registries in the Docker Engine Setting like this:
![image](https://user-images.githubusercontent.com/107843812/188176408-9e0c757f-46bd-4dac-aaa9-36e61b01e2fc.png)

The previous given that we didn't find the `config` folder to create the daemon.json file. Is this a correct approach or where exactly the daemon.json must be? 

Thank you for the help,
Mateo Toro (R&D Nester)

**Comment by ferdinandobosco** [comment]
Solved. See #3
