### ISSUE TITLE
Security policy issue

### ISSUE THREAD

**Issue by adeimv** [european-dynamics-rnd/OneNet#7]
Hello,
I am Amila from EIMV.
Following your guidelines, we successfully installed the connector on our Linux server, but now we have a problem.
Our Institute has a security policy that does not allow "Data App" and "Ecc Url" to be publicly exposed (ports 8084 and 8889). We are trying to find a way to allow this, but did anyone else have this problem? How did they solve it?
Thank you in advance.

**Comment by HeliasEurodyn** [comment]
Hello @adeimv. 
Unfortunately this is mandatory. 
By the Onenet Architecture, the required files to be transferd from/to your premisses to other consumers/providers are shared peer to peer, through those Ips/Ports.
